spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.ecommerce.notification.event.OrderPlacedEvent
        spring.json.use.type.headers: false

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

logging:
  file:
    name: /app/logs/notification-service.log
